### ISSUE TITLE
Matrix4d::inverse() and -ffast-math

### ISSUE THREAD

**Issue by vlarsson** [vlarsson/PoseLib#13]
Building with -ffast-math and without -march=native with GCC 7.5 breaks every solver that depends on Eigen::Matrix4d::inverse(). I have verified that inverse() actually yields incorrect results in this case. (A * A.inverse() = diag([1 -1 1 -1]) )

Building with Clang it seems to work, so it is unclear whether this bug is in Eigen or GCC (or this code :))

Tested on Ubuntu 18.04.

**Comment by ishipachev** [comment]
But building with fast-math breaks some floating point standart compatability, isn't it?
https://kristerw.github.io/2021/10/26/fast-math-ub/

**Comment by vlarsson** [comment]
I did some preliminary testing and removing `-funsafe-math-optimizations` makes it work again while still retaining some of the benefit from `-ffast-math`. So compiling with `-ffast-math -fno-unsafe-math-optimizations` seems work. This will be the default in a future commit, but it would be good to do some more testing to figure out what the best options are.
