### ISSUE TITLE
pose problem with unknown principal point

### ISSUE THREAD

**Issue by yuguangxie** [vlarsson/PoseLib#16]
Hello, Larsson
Thank you for sharing the code. After carefully reading their related literature，I'm interested in your research on pose problem with unknown principal point. Especially, the article "Camera pose estimation with unknown principal point" published in CVPR 2018 is closely related to my current research work. 
If it is convenient to you, could you share the code of this article with us？

**Comment by vlarsson** [comment]
Hi,
there is currently no plan to include the unknown principal point solvers into PoseLib (since it mainly deals with calibrated problems), however, if you send me an email I can send you the code for the CVPR 18 paper.

Best,
Viktor

**Comment by alexs7** [comment]
@vlarsson is the code in PoseLib ?

**Comment by vlarsson** [comment]
@alexs7 the code is currently not in PoseLib. It's on my todo to add instrinsic refinement and once this is added I plan to add all of the corresponding solvers for unknown intrinsics.
