### ISSUE TITLE
Alignment issues with Eigen

### ISSUE THREAD

**Issue by vlarsson** [vlarsson/PoseLib#21]
Currently alignment for Eigen is not correctly handled.

**Comment by vlarsson** [comment]
I made an initial commit here (https://github.com/vlarsson/PoseLib/tree/alignment) which adds specialization to vector with aligned allocators. I still need to test it and figure out if it actually solves the problem.

**Comment by kunalchelani** [comment]
Just came across this myself as in my own project I was using `std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d>>` but had to populate another container before using Poselib. Waiting for you to figure out if your specialization solves the problem.

**Comment by vlarsson** [comment]
As far as I understand, compiling with C++17 resolves all of these issues. This seems like the least effort solution right now. I will close this issue.
