### ISSUE TITLE
p4pf usage

### ISSUE THREAD

**Issue by JakubReha** [vlarsson/PoseLib#25]
Hi,
I have a question about using the p4pf implementation. I have the pixel coordinates, corresponding world coordinates and the principal point. First, I subtract the principal point [o_x, o_y] from the pixel coordinates [u, v] and then I pass these x=[u - o_x, v - o_y, 1] as the image coordinates together with the world coordinates X to the solver. Then , I am trying to project the world points X using the obtained rotation and translation together with the camera matrix (composed from the principal point and the obtained focal length), but these projections are far off from the original pixel coordinates. Is there something that I am doing wrong?

**Comment by nosy-b** [comment]
@JakubReha Good question. I'm actually doing the same and get weird results too!

@vlarsson @pablospe Do you have some tips for us?  Thanks! :)

My code: 
```
    // Image size: 560px * 840px.  Center = 280, 420
    // pixel coordinates of the 4 points (315, 217),  (361, 295),  (392, 660),  (146, 220)

    Eigen::Vector3d imgA(315 - 280, 217 - 420, 1);
    Eigen::Vector3d imgB(361 - 280, 295 - 420, 1);
    Eigen::Vector3d imgC(392 - 280, 660 - 420, 1);
    Eigen::Vector3d imgD(146 - 280, 220 - 420, 1);
    std::vector<Eigen::Vector3d> pointsImage = { imgA, imgB, imgC, imgD};

    // Corresponding 3D points in my scene
    Eigen::Vector3d a(-20.96, 3.54, 13.86);
    Eigen::Vector3d b(-20.96, 3.57, 13.24);
    Eigen::Vector3d c(-20.95, 2.01, 13.25);
    Eigen::Vector3d d(-21.66, 3.74, 13.86);
    std::vector<Eigen::Vector3d> points3D = { a, b, c, d };
    
    std::vector<pose_lib::CameraPose> output;
    int result = pose_lib::p4pf(pointsImage, points3D,  &output, true);
```

_Results : 
Best pose Rotation:
  0.951549 -0.0239519  -0.363001
 -0.162092  -0.896018  -0.365775
 -0.316605   0.407035  -0.856787
best pose translation: 25.1887, 4.10001, 6.6931
best pose focal: 789.804_
