### ISSUE TITLE
PoseLib/robust/colmap_models.h: No such file or directory

### ISSUE THREAD

**Issue by yocabon** [vlarsson/PoseLib#38]
https://github.com/vlarsson/PoseLib/blob/master/PoseLib/robust/jacobian_impl.h#L34
should probably be 
```
#include "PoseLib/misc/colmap_models.h"
```

**Comment by vlarsson** [comment]
Thanks for catching this. Fixed in e06026533f39313b00097d1c38ee69cccee29c6c I have no idea how I missed this one :)
