### ISSUE TITLE
Degeneracies for 180 degree rotations

### ISSUE THREAD

**Issue by vlarsson** [vlarsson/PoseLib#4]
Currently many solvers are degenerate for exactly 180 degree rotations. This should either be fixed, or at least documented.

**Comment by tsattler** [comment]
In case a degeneracy is observed, you could randomly rotate the scene and run the solver again.

**Comment by pablospe** [comment]
Which solver are degenerate for these rotations? I think the ones using cayley parametrization should be ok by contruction, right?

**Comment by vlarsson** [comment]
Most of the solvers that rely on the 3Q3 solver degenerates for exactly 180 degree rotations. This seems to be mostly a problem with synthetic data, as shifting the GT rotation by some epsilon (I tried 0.001 radians), seems to fix it.

 You can try this by adding
 pose.R << -1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0;
to setup_random_pose in the benchmarking code. I think the problem partly stems from the automatic variable selecting in RE3Q3 not working as intended. 

Adding a random rotation should fix the problem as well. I will do some testing with this to see how much of performance loss it is. If you force affine change of variables in the 3Q3 code it also becomes stable, though I think this should be more expensive, so I will benchmark this as well.

**Comment by vlarsson** [comment]
I added a random rotations for all RE3Q3 solvers (see f0ca0d076d3ede9730dfece05890e120f46684a8). There is some runtime penalty, but I think it is an acceptable trade-off. Possibly we could add compile-time flags to disable it later.

There is still an issue with the upright solvers that rely on the Weierstrass substitution to parameterize the rotations. I will implement the same for these later.

**Comment by vlarsson** [comment]
This seems to be solved, expect for upright solvers for which there is another issue #7
