### ISSUE TITLE
derivation of up2p

### ISSUE THREAD

**Issue by LoFaiTh** [vlarsson/PoseLib#46]
Could you share some derivation material of up2p, especially from line 35 to line 52 in up2p.cc? I tried some times, just couldn't figure out how this part works. Thanks a lot.

**Comment by vlarsson** [comment]
I don't have them easily available right now, but the basic idea is (probably) like this.

Parameterize the rotation (scaled by (1+q^2)) as 
```
R = [1-q^2 0 2*q;
       0 1+q^2 0;
      -2*q 0 1-q^2]
```

From the reprojection equations we get 4 equations in the monomials (q^2, q, t1, t2, t3, 1) where we have absorbed (1+q^2) into each tk.

The A matrix in the code corresponds to the monomials [t1, t2, t3, q^2], and b to [q, 1], so

A * [t1,t2,t3,q^2] + b * [q, 1] = 0

Multiplying with inv(A) gives the last equation being a quadratic in q.

Hopefully this helped.

**Comment by LoFaiTh** [comment]
> From the reprojection equations we get 4 equations in the monomials (q^2, q, t1, t2, t3, 1) where we have absorbed (1+q^2) into each tk.
This is where I get confused. If tk scaled up by (1+q^2), you get q^2*tk. How to eliminate this to get monomials?

**Comment by vlarsson** [comment]
Ah okay, by absorbed into tk, I mean that we introduce new variables
t1_hat = (1+q^2)*t_1
etc and solve for these new variables instead. Then once we have t1_hat and q, we can recover t_1 by dividing by (1+q^2).

In the code this happens here
https://github.com/vlarsson/PoseLib/blob/master/PoseLib/solvers/up2p.cc#L71

Let me know if anything else is unclear.

**Comment by LoFaiTh** [comment]
Clear. I've been stuck on this matter for like two days. Thanks a lot.
