### ISSUE TITLE
GeneralizedRelativePoseEstimator always uses 0th and 1st pair for 5p1pt

### ISSUE THREAD

**Issue by v-pnk** [vlarsson/PoseLib#54]
Hi,
I think there is a bug in [`relative_pose.cc`](https://github.com/vlarsson/PoseLib/blob/bf48ad35ceeccab71d0b8bd7b34538c2e889a731/PoseLib/robust/estimators/relative_pose.cc) [`GeneralizedRelativePoseEstimator::generate_models`](https://github.com/vlarsson/PoseLib/blob/bf48ad35ceeccab71d0b8bd7b34538c2e889a731/PoseLib/robust/estimators/relative_pose.cc#L78).

The `pair0` and `pair1` variables are defined and initialized to 0 and 1 before the while loop ([here](https://github.com/vlarsson/PoseLib/blob/bf48ad35ceeccab71d0b8bd7b34538c2e889a731/PoseLib/robust/estimators/relative_pose.cc#L82)) and then redefined inside the loop ([here](https://github.com/vlarsson/PoseLib/blob/bf48ad35ceeccab71d0b8bd7b34538c2e889a731/PoseLib/robust/estimators/relative_pose.cc#L84) and [here](https://github.com/vlarsson/PoseLib/blob/bf48ad35ceeccab71d0b8bd7b34538c2e889a731/PoseLib/robust/estimators/relative_pose.cc#L88)). That results in loss of the values assigned to `pair0` and `pair1` inside the while loop when the program counter gets outside of it and `pair0` and `pair1` stay at the values assigned before the loop (0 and 1 respectively).

Removing the variable type definition inside the loop (`int pair0 = ...` &#8594; `pair0 = ...` and `int pair1 = ...` &#8594; `pair1 = ...`) should resolve the issue.

**Comment by vlarsson** [comment]
Thanks, that is indeed a bug! I was only testing it on pairs of cameras so it has gone unnoticed :)

However, I also wrote the code before the general 6pt solver was implemented, but I think it should probably be migrated to use this one instead (which require some more complex sampling). In some internal benchmarks it seemed to perform better.

**Comment by tsattler** [comment]
Actually, we are using it for the semi-generalized case, so this is relevant for us :)

I guess I should run my experiments again :)

**Comment by tsattler** [comment]
Created a pull request for this one.

**Comment by vlarsson** [comment]
Thanks! I've merged the fix now.
